# Generated by Django 4.0.2 on 2022-03-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
